spring:
  application:
    name: cp-auth-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth_db
    username: root
    password: root
    pool:
      initial-size: 3
      max-size: 10
      max-idle-time: 10m
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/auth_db
    user: root
    password: root
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      password: root
grpc:
  server:
    port: 9090
    security:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

info:
  app:
    name: cp-auth-service
    description: Auth service for CP platform (dev)
    version: 0.1.0-dev

app:
  jwt:
    token:
      expiration:
        access: 3600
        refresh: 2592000
      issuer: "auth-service"
    rsa:
      private-key-path: "keys/private_key.pem"
      public-key-path: "keys/public_key.pem"
  cache:
    caffeine:
      default-ttl: 300  # 5 minutes
      user-context-ttl: 300  # 5 minutes
      role-cache-ttl: 600   # 10 minutes
    redis:
      blacklist-ttl: 86400  # 24 hours

