spring:
  application:
    name: cp-auth-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth_db
    username: root
    password: root
    pool:
      initial-size: 3
      max-size: 10
      max-idle-time: 10m
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/auth_db
    user: root
    password: root
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      password: root

server:
  port: ${SERVER_PORT:8080}

management:
#  server:
#    port: ${MANAGEMENT_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

# Optional: Add actuator info for dev
info:
  app:
    name: cp-auth-service
    description: Auth service for CP platform (dev)
    version: 0.1.0-dev
