spring:
  profiles:
    active: dev

  application:
    name: cp-auth-service

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG